function model = trainSVM(XTrain,YTrain)

% ============================================================
% SUPPORT VECTOR MACHINE
% ============================================================

fprintf('\n');
fprintf('============================================\n');
fprintf('TRAINING SVM\n');
fprintf('============================================\n');

% RBF binary learner
template = templateSVM( ...
    'KernelFunction','rbf', ...
    'KernelScale','auto', ...
    'BoxConstraint',1, ...
    'Standardize',false);

% Multiclass ECOC model
model = fitcecoc( ...
    XTrain, ...
    YTrain, ...
    'Learners',template, ...
    'Coding','onevsone', ...
    'Prior','uniform', ...
    'Verbose',0);

fprintf('SVM training completed.\n');

end